import { api } from '../core/api.js';
import { auth } from '../core/auth.js';
async function init() {
  if (!auth.requireAuth('admin')) return;
  const app = document.querySelector('#app'); const state = { products: [] }; const list = app.querySelector('#list'); const detail = app.querySelector('#detail');
  const renderList = () => { const q = app.querySelector('#search').value.toLowerCase(); list.innerHTML = state.products.filter(product => product.name.toLowerCase().includes(q)).map(product => `<button class="list-item" data-id="${product.id}"><strong>${product.name}</strong><span class="muted">${product.unit_type} · ${product.quantity}</span></button>`).join(''); list.querySelectorAll('[data-id]').forEach(button => button.onclick = () => showProduct(state.products.find(product => product.id === Number(button.dataset.id)))); };
  const showProduct = product => { const value = product || { name: '', unit_type: 'piece', sale_price: '', purchase_price: '', price_per_kg: '', price_per_piece: '', price_per_carton: '', pieces_per_carton: '' }; detail.innerHTML = `<form id="product-form" class="stack"><h2>${product ? 'تعديل المنتج' : 'منتج جديد'}</h2><label class="label">الاسم<input class="input" name="name" required value="${value.name}"></label><label class="label">الوحدة<select class="select" name="unit_type"><option value="piece">قطعة</option><option value="weight">وزن</option><option value="carton">كرتون</option></select></label><label class="label">الباركود<input class="input" name="barcode" value="${value.barcode || ''}"></label><label class="label">سعر البيع<input class="input" name="sale_price" type="number" step="0.01" value="${value.sale_price ?? ''}"></label><label class="label">سعر الشراء<input class="input" name="purchase_price" type="number" step="0.01" value="${value.purchase_price ?? ''}"></label><label class="label">سعر الكيلو<input class="input" name="price_per_kg" type="number" step="0.01" value="${value.price_per_kg ?? ''}"></label><label class="label">سعر القطعة<input class="input" name="price_per_piece" type="number" step="0.01" value="${value.price_per_piece ?? ''}"></label><label class="label">سعر الكرتون<input class="input" name="price_per_carton" type="number" step="0.01" value="${value.price_per_carton ?? ''}"></label><label class="label">قطع الكرتون<input class="input" name="pieces_per_carton" type="number" min="1" value="${value.pieces_per_carton ?? ''}"></label><button class="btn btn-primary">حفظ</button><div id="message"></div></form>`; detail.querySelector('[name=unit_type]').value = value.unit_type; detail.querySelector('form').onsubmit = async event => { event.preventDefault(); const form = new FormData(event.target); const payload = { name: form.get('name'), barcode: form.get('barcode') || undefined, unit_type: form.get('unit_type'), sale_price: Number(form.get('sale_price')) || undefined, purchase_price: Number(form.get('purchase_price')) || undefined, price_per_kg: Number(form.get('price_per_kg')) || undefined, price_per_piece: Number(form.get('price_per_piece')) || undefined, price_per_carton: Number(form.get('price_per_carton')) || undefined, pieces_per_carton: Number(form.get('pieces_per_carton')) || undefined }; await (product ? api.put(`/api/products/${product.id}`, payload) : api.post('/api/products', payload)); event.target.querySelector('#message').textContent = 'تم الحفظ.'; state.products = (await api.get('/api/products')).products || []; renderList(); }; };
  app.querySelector('#new').onclick = () => showProduct(); app.querySelector('#search').oninput = renderList; app.querySelector('#category').onsubmit = async event => { event.preventDefault(); const form = new FormData(event.target); await api.post('/api/categories', { name: form.get('name'), low_stock_threshold: Number(form.get('low_stock_threshold')) }); event.target.reset(); }; state.products = (await api.get('/api/products')).products || []; renderList();
}
document.addEventListener('DOMContentLoaded', init);
