import { api } from '../core/api.js';
import { auth } from '../core/auth.js';
async function init() {
  if (!auth.requireAuth('admin')) return;
  const app = document.querySelector('#app'); const [promotions, products] = await Promise.all([api.get('/api/promotions?active=false'), api.get('/api/products')]); const list = app.querySelector('#list');
  const show = promo => { const value = promo || { product_id: '', promo_type: 'percent_off', value: '', bundle_quantity: '', until_stock_zero: false }; app.querySelector('#detail').innerHTML = `<form id="form" class="stack"><h2>${promo ? 'تعديل العرض' : 'عرض جديد'}</h2><label class="label">المنتج<select class="select" name="product_id">${(products.products || []).map(p => `<option value="${p.id}">${p.name}</option>`).join('')}</select></label><label class="label">النوع<select class="select" name="promo_type"><option value="percent_off">نسبة خصم</option><option value="fixed_price">سعر ثابت</option><option value="bundle">حزمة</option></select></label><label class="label">القيمة<input class="input" name="value" type="number" min="0" step="0.01" required value="${value.value}"></label><label class="label">كمية الحزمة<input class="input" name="bundle_quantity" type="number" min="1" value="${value.bundle_quantity || ''}"></label><label class="label">ينتهي عند نفاد المخزون<input type="checkbox" name="until_stock_zero" ${value.until_stock_zero ? 'checked' : ''}></label><button class="btn btn-primary">حفظ</button><div id="message"></div></form>`; app.querySelector('[name=product_id]').value = value.product_id; app.querySelector('[name=promo_type]').value = value.promo_type; app.querySelector('#form').onsubmit = async event => { event.preventDefault(); const data = new FormData(event.target); const payload = { product_id: Number(data.get('product_id')), promo_type: data.get('promo_type'), value: Number(data.get('value')), bundle_quantity: Number(data.get('bundle_quantity')) || undefined, until_stock_zero: data.has('until_stock_zero') }; await (promo ? api.put(`/api/promotions/${promo.id}`, payload) : api.post('/api/promotions', payload)); event.target.querySelector('#message').textContent = 'تم الحفظ.'; }; };
  list.innerHTML = (promotions.promotions || []).map(promo => `<button class="list-item" data-id="${promo.id}"><strong>${promo.promo_type}</strong><span class="muted">${promo.value}</span></button>`).join(''); list.querySelectorAll('[data-id]').forEach(button => button.onclick = () => show((promotions.promotions || []).find(p => p.id === Number(button.dataset.id)))); app.querySelector('#new').onclick = () => show();
}
document.addEventListener('DOMContentLoaded', init);
